services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5000:80"  
    depends_on:
      - authservice
      - orderservice
      - trackingservice
    networks:
      - mynetwork

  authservice:
    image: ${DOCKER_REGISTRY-}authservice
    ports:
      - "5001:80"
    build:
      context: .
      dockerfile: AuthService/Dockerfile
    networks:
      - mynetwork
    depends_on:
      - sqlserver



  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    ports:
      - "5002:80"
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    networks:
      - mynetwork
    depends_on:
      - sqlserver

  trackingservice:
    image: ${DOCKER_REGISTRY-}trackingservice
    ports:
      - "5003:80"
    build:
      context: .
      dockerfile: TrackingService/Dockerfile
    networks:
      - mynetwork
    depends_on:
      - sqlserver
  
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword123
    ports:
      - "1433:1433" 
    networks:
      - mynetwork
    volumes:
      - sql_data:/var/opt/mssql


networks:
  mynetwork:
    driver: bridge
